portal_base_controller:
    pattern: /portal
    defaults: { _controller: phpbbireland.portal.controller:portal, forum_id: 0, year: 0, month: 0, page: 1 }

portal_base_page_controller:
    pattern: /portal/page/{page}
    defaults: { _controller: phpbbireland.portal.controller:portal, page: 0 }
    requirements:
        page:      \d+

